name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.4
  charset_converter: ^2.0.0
  flutter_riverpod: ^1.0.1
  
  # firebase
  firebase_core: ^1.10.2
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.3.0
  cloud_firestore: ^3.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Source Han Sans JP ExtraLight
      fonts:
        - asset: assets/fonts/SourceHanSansJP-ExtraLight.otf
    - family: Source Han Sans JP Light
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Light.otf
    - family: Source Han Sans JP Normal
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Normal.otf
    - family: Source Han Sans JP Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf
    - family: Source Han Sans JP Medium
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Medium.otf
    - family: Source Han Sans JP Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: Source Han Sans JP Heavy
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Heavy.otf
  
  assets:
    - assets/syukujitsu.csv
