name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # $ flutter pub get 未取得のパッケージを取得
  # $ flutter pub upgrade 最新版のパッケージを取得
  # $ flutter pub outdated 更新可能なパッケージのチェック
  # $ flutter pub deps 依存関係のチェック

  charset_converter: ^2.1.0
  cupertino_icons: ^1.0.4
  flutter_riverpod: ^1.0.3
  routemaster: ^0.9.5
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.11
  firebase_database: ^9.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Source Han Sans JP
      fonts:
        - asset: assets/fonts/SourceHanSansJP-ExtraLight.otf
          weight: 100
        - asset: assets/fonts/SourceHanSansJP-Light.otf
          weight: 200
        - asset: assets/fonts/SourceHanSansJP-Normal.otf
          weight: 300
        - asset: assets/fonts/SourceHanSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/SourceHanSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/SourceHanSansJP-Heavy.otf
          weight: 800
    - family: Zen Kaku Gothic Antique
      fonts:
        - asset: assets/fonts/ZenKakuGothicAntique-Light.ttf
          weight: 300
        - asset: assets/fonts/ZenKakuGothicAntique-Regular.ttf
          weight: 400
        - asset: assets/fonts/ZenKakuGothicAntique-Medium.ttf
          weight: 500
        - asset: assets/fonts/ZenKakuGothicAntique-Bold.ttf
          weight: 700
        - asset: assets/fonts/ZenKakuGothicAntique-Black.ttf
          weight: 900

  assets:
    - assets/syukujitsu.csv
