name: テストアクション

on:
  push:
    branches:
      - 'feat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'master'
          destination_branch: 'feat/test'
          pr_title: 'テストPR'
          github_token: ${{ secrets.GITHUB_TOKEN }}
