name: テストアクション

on:
  push:
    branches:
      - 'feat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.BRANCH_NAME }}
          destination_branch: 'master'
          pr_title: ${{ env.BRANCH_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
      
      - name: output-has-changed-files
        run: echo ${{steps.open-pr.outputs.has_changed_files}}
